services:
  - type: web
    name: umnyj-yurist-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: OCR_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
